### ISSUE TITLE
[FEATURE] US 6 | TK 15 Develop Front-end of First Variation Screen of Ongoing Challenge (Duel)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#107]
# Title ✏️ 
> Develop Front-end of First Variation Screen of Ongoing Challenge (Duel)

# Description 📝
## Project Info 📈
> - US **06**
> - Task 
    - ID: **15**
    - Title: **Develop Front-end of First Variation Screen of Ongoing Challenge (Duel)**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail how this feature should be implemented.

<img width="293" alt="Screen Shot 2022-08-04 at 10 52 14" src="https://user-images.githubusercontent.com/69223192/182864112-5945c88e-7c01-4a05-8000-5933e4da41ce.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #122
