### ISSUE TITLE
[FEATURE] US 3 | TK 16 Develop Front-end of Second Variation Screen of Ongoing Challenge (3/4 Participants)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#108]
# Title ✏️ 
> Develop Front-end of Second Variation Screen of Ongoing Challenge (3/4 Participants)

# Description 📝
## Project Info 📈
> - US **03**
> - Task 
    - ID: **16**
    - Title: **Develop Front-end of Second Variation Screen of Ongoing Challenge (3/4 Participants)**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
<img width="443" alt="Screen Shot 2022-08-04 at 10 54 16" src="https://user-images.githubusercontent.com/69223192/182864570-bdfe95f0-b10c-4d2d-a5fd-c49a4a5ff8fb.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #127
