### ISSUE TITLE
[FEATURE] US 3 | TK 17 Develop Front-end Score Controller Component of Ongoing Challenge Screen (3/4 Participants)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#109]
# Title ✏️ 
> Develop Front-end Score Controller Component of Ongoing Challenge Screen (3/4 Participants)

# Description 📝
## Project Info 📈
> - US **03**
> - Task 
    - ID: **17**
    - Title: **Develop Front-end Score Controller Component of Ongoing Challenge Screen (3/4 Participants)**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

<img width="173" alt="Screen Shot 2022-08-04 at 10 57 48" src="https://user-images.githubusercontent.com/69223192/182865362-413b02c9-a464-4767-a475-bbd98f102734.png">
<img width="176" alt="Screen Shot 2022-08-04 at 10 58 01" src="https://user-images.githubusercontent.com/69223192/182865416-f1dce35b-fb16-462d-a9f0-b050c463004b.png">

<img width="177" alt="Screen Shot 2022-08-04 at 10 57 32" src="https://user-images.githubusercontent.com/69223192/182865298-3237a00f-046f-4f10-b177-d880eb2f963d.png">

<img width="175" alt="Screen Shot 2022-08-04 at 10 56 16" src="https://user-images.githubusercontent.com/69223192/182865024-e9c2a970-eada-4229-bdd7-fe6b6197d513.png">
rcontent.com/69223192/182864980-77448dc8-e8f7-484a-9897-7a6b6e9839a0.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
closed by #124
