### ISSUE TITLE
[FEATURE] US 3 | TK 18 Develop Front-end Scoreboard Component of Ongoing Challenge Screen (3/4 Participants)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#110]
# Title ✏️ 
> Develop Front-end Scoreboard Component of Ongoing Challenge Screen (3/4 Participants)

# Description 📝
## Project Info 📈
> - US **03**
> - Task 
    - ID: **18**
    - Title: **Develop Front-end Scoreboard Component of Ongoing Challenge Screen (3/4 Participants)**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

<img width="177" alt="Screen Shot 2022-08-04 at 10 59 44" src="https://user-images.githubusercontent.com/69223192/182865851-bf6eae0c-cd78-4686-af5b-0c7a59f4df9a.png">
<img width="179" alt="Screen Shot 2022-08-04 at 11 00 00" src="https://user-images.githubusercontent.com/69223192/182865916-8c776345-40ea-4266-b20e-87df54068242.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #125
