### ISSUE TITLE
[FEATURE] US 3 | TK 23 Develop Front-end Cell Component of Challenges List

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#111]
# Title ✏️ 
> Develop Front-end Cell Component of Challenges List

# Description 📝
## Project Info 📈
> - US **03**
> - Task 
    - ID: **23**
    - Title: **Develop Front-end Cell Component of Challenges List**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

<img width="530" alt="Screen Shot 2022-08-04 at 11 04 18" src="https://user-images.githubusercontent.com/69223192/182866888-eef6a863-a957-40fa-9f39-b1e66486b0d0.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Resolved at #117 117
