### ISSUE TITLE
[FEATURE - 3] US 10 | TK 17 Develop Alert When Deleting Account

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#133]
# Title ✏️ 
> Develop Alert When Deleting Account

# Description 📝
## Project Info 📈
> - US **10**
> - Task 
    - ID: **26**
    - Title: **Develop Alert When Deleting Account**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

<img width="456" alt="Screen Shot 2022-08-16 at 16 04 07" src="https://user-images.githubusercontent.com/69223192/184961391-d1b891e2-379c-4afe-a5c1-841a01e27c95.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #165
