### ISSUE TITLE
[FEATURE - 8] US 06 | TK 13 Develop Front/Back-end Integration of Ongoing Challenges

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#134]
# Title ✏️ 
> Develop Front/Back-end Integration of Ongoing Challenges

# Description 📝
## Project Info 📈
> - US **06**
> - Task 
    - ID: **27**
    - Title: **Develop Front/Back-end Integration of Ongoing Challenges**
 
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail how this feature should be implemented.

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #176
