### ISSUE TITLE
[BUG - 8] US 03 | TK 26 Develop Fix for PopToRootViewController function after creating challenge (Keeps popping to Challenge Type Selection)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#135]
# Title ✏️
> Develop Fix for PopToRootViewController function after creating challenge (Keeps popping to Challenge Type Selection)

# Description 📝
## Current behaviour 🚫
> Here is an Issue Description. Please, insert richer details about the Bug being reported. Describe in words the current behaviour. 

## Expected Behaviour ✅
> After create a challenge, when the user click on return, the should returns to challenges list, not for the creation screen...

# **How to Reproduce** 🪞
Steps to reproduce the behaviour:
1. Create a challenge
2. Click on on return

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Alredy integrated on main branch
