### ISSUE TITLE
[IMPROVEMENT - 3] US 04 | TK 3 Develop List Deletion Fix (Fix Index Update When Deleting Challenges)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#138]
# Title ✏️ 
> Develop List Deletion Fix (Fix Index Update When Deleting Challenges)

# Description 📝
## What's wrong with the current behaviour ❓
> The app delete the correct challenge on server, but visually don't

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail what this improvement should look like.

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #169
