### ISSUE TITLE
[FEATURE - 3] US 06 | TK 27 Develop Front-end Integration for Ongoing Screens

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#139]
# Title ✏️ 
> Develop Front-end Integration for Ongoing Screens

# Description 📝
## Project Info 📈
> - US **06**
> - Task 
    - ID: **33**
    - Title: **Develop Front-end Integration for Ongoing Screens**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail how this feature should be implemented.

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by  #167
