### ISSUE TITLE
[IMPROVEMENT - 2] US 04 | TK 6 Develop Challenges List Filter (Most Recent First)

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#141]
# Title ✏️ 
> Develop Challenges List Filter (Most Recent First)

# Description 📝
## What's wrong with the current behaviour ❓
> After create a challenge, the list of challenge must be updated, and the most recent challenge should appear as the first challenge in the list.

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail what this improvement should look like.

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #169
