### ISSUE TITLE
[IMPROVEMENT - 2] US 05 | TK 10 Develop Transparancy Fix on Duel Score Controller Component

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#142]
# Title ✏️ 
> Develop Transparancy Fix on Duel Score Controller Component

## What could be improved ✅
> Add transparency to the Duel Score component

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail what this improvement should look like.

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #152
