### ISSUE TITLE
[FEATURE - 3] US 08 | TK 16 Develop User Profile Screen

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#144]
# Title ✏️ 
> Develop User Profile Screen

# Description 📝
## Project Info 📈
> - US **08**
> - Task 
    - ID: **37**
    - Title: **Develop User Profile Screen**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
<img width="329" alt="Screen Shot 2022-08-16 at 16 27 30" src="https://user-images.githubusercontent.com/69223192/184965376-a5b6816d-fe4e-4513-a592-ce224d4fdb56.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #165
