### ISSUE TITLE
[FEATURE - 3] US 10 | TK 18 Develop Alert Error When Deleting Account Is not Possible

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#145]
# Title ✏️ 
> Develop Alert Error When Deleting Account Is not Possible

# Description 📝
## Project Info 📈
> - US **10**
> - Task 
    - ID: **39**
    - Title: **Develop Alert Error When Deleting Account Is not Possible**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
<img width="334" alt="Screen Shot 2022-08-16 at 16 29 57" src="https://user-images.githubusercontent.com/69223192/184965810-4495afcd-a8da-4c2b-abbc-e7b505871317.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #165
