### ISSUE TITLE
[IMPROVEMENT - 2] US 01 | TK 28 Develop Terms of Use Update on Text Label

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#147]
# Title ✏️ 
> Develop Terms of Use Update on Text Label

# Description 📝
## What's wrong with the current behaviour ❓
> Terms of use do not contain UXCam on it

## What could be improved ✅
> Should improve our  Terms of use to cover the use of UXCam on the app

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail what this improvement should look like.

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #163
