### ISSUE TITLE
[FEATURE - 2] US 08 | TK 15 Develop User Profile Picture Component

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#148]
# Title ✏️ 
> Develop User Profile Picture Component

# Description 📝
## Project Info 📈
> - US **08**
> - Task 
    - ID: **52**
    - Title: **Develop User Profile Picture Component**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
<img width="169" alt="Screen Shot 2022-08-16 at 16 46 09" src="https://user-images.githubusercontent.com/69223192/184970857-3dc9b9fe-9152-4877-9b6b-9cd295b760f3.png">

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #165
