### ISSUE TITLE
[FEATURE] US 3 | TK 14 Develop Quick Challenge Creation Screen [5]

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#43]
#  Develop Quick Challenge Creation Screen ✏️ 

# Description 📝
## Project Info 📈
> - US **03**
> - Task 
    - ID: **14**
    - Title: **Develop Quick Challenge Creation Screen**

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
If applicable, add screenshots from Figma to help detail how this feature should be implemented.

To do Add Figma ScreenShot when available

## Designer Notes 🤓🎨

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #106
