### ISSUE TITLE
[IMPROVEMENT] US 1 | TK 23 Develop Support Dynamic Types on Registration Screen [3]

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#46]
# Develop Support Dynamic Types on Registration Screen ✏️ 

# Description 📝
## What could be improved ✅
The Registration Screen must be able to adapt itself to the Dynamic types whenever the user wants

**Additional context** 🌎

**Comment by MarinaFX** [comment]
Closed by #82
