### ISSUE TITLE
[FEATURE] US 01 | TK 30 Develop Error Feedback [2]

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#54]
# Develop an Error Feedback when the User inputs a non valid email on Registration Screen ✏️ 

# Description 📝
## Project Info 📈
> - US **01**
> - Task 
    - ID: **30**
    - Title: **Develop an Error Feedback when the User inputs a non valid email on Registration Screen**

## Expected Behaviour ✅
Develop and error alert that shakes de screen and change the textFiel colors...

**Comment by MarinaFX** [comment]
Closed by #86
