### ISSUE TITLE
[FEATURE] US 01,02,03,04 and US05 | TK 31 Automate APIs Routes Documentation [13]

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#57]
# Automate APIs Routes Documentation ✏️ 

# Description 📝
## Project Info 📈
> - US **US 01,02,03,04 and US05**
> - Task 
    - ID: **31**
    - Title: **Automate APIs Routes Documentation**

## Expected Behaviour ✅
> Here is another Issue Description. Please, insert richer details about the expected behaviour. Describe in words how the code should behave, inputs and outputs. 

**Additional context** 🌎

**Comment by MarinaFX** [comment]
No longer being developed for current sprint
