### ISSUE TITLE
[FEATURE] US 02 | TK 35 Develop connection from login to Home Screen (blank screen for now) [2]

### ISSUE THREAD

**Issue by jgabrielbiazus** [MarinaFX/Fiero#63]
# Develop connection from login to Home Screen (blank screen for now) ✏️ 

# Description 📝
## Project Info 📈
> - US **02**
> - Task 
    - ID: **35**
    - Title: **Develop connection from login to Home Screen (blank screen for now)**

**Comment by MarinaFX** [comment]
Implemented on #96
