### ISSUE TITLE
[FEATURE] US 4 | TK 71 Develop ChallengesTypeCell Component - List

### ISSUE THREAD

**Issue by illuminatyy** [MarinaFX/Fiero#92]
# Develop ChallengesTypeCell Component - List ✏️ 

# Description 📝
## Project Info 📈
> - US **4**
> - Task 
    - ID: **71**
    - Title: **Develop ChallengesTypeCell Component - List**

## Expected Behaviour ✅
Implement Challenge Type Component 

# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

<img width="1250" alt="Screenshot from Figma Component Hand-off" src="https://user-images.githubusercontent.com/51174686/179847965-175684ff-b3ff-492a-b7e3-759ae27c1921.png">

**Comment by MarinaFX** [comment]
Closed by #91
